spring.application.name=spring2
#Port configuration
server.port=8081 

#DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/StudentDb
spring.datasource.username=postgres
spring.datasource.password=Achyut@1235

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true 
spring.jpa.properties.hibernate.format_sql=true

server.servlet.context-path=/api
